name: CraftableSherds
version: '${project.version}'
main: me.gabemoreno.craftablesherds.CraftableSherds
api-version: 1.20
authors: [ gabemoreno ]
description: Create custom crafting recipes for pottery sherds.

commands:
  csreload:
    description: Reload all custom recipes.
    usage: /<command>
    aliases: [csr]
    permission: craftablesherds.reload